version: 2

anchors:
  default-config: &default-config
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: dependabot-base

updates:
  - package-ecosystem: "gomod"
    <<: *default-config
  - package-ecosystem: "github-actions"
    <<: *default-config
