# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: vrsn
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X "github.com/thaffenden/pkb/cmd.Version={{.Version}}"
