name: go build and test

on:
  push:
    branches-ignore:
      - $default-branch
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'
    permissions:
      contents: read
    types: [opened, reopened]

anchors:
  go-version: &go-version 1.18

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: *go-version
      - name: build binary
        run: make build
      - name: test
        run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        name: Set up Go
        with:
          go-version: *go-version
      - uses: golangci/golangci-lint-action@v3
        name: golangci-lint
        with:
          version: latest
