name: go build and test

on:
  push:
    branches-ignore:
      - main
  pull_request:
    permissions:
      contents: read
    types: [opened, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: build binary
        run: make build
      - name: test
        run: |
          TEST_OUTPUT=$(make test | ./scripts/parse-tests.sh)
          echo "$TEST_OUTPUT" > "$GITHUB_STEP_SUMMARY"
          echo "$GITHUB_STEP_SUMMARY"
