name: golangci-lint

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**.go'
  pull_request:
    permissions:
      contents: read
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        name: Set up Go
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@v3
        name: golangci-lint
        with:
          version: latest
